#!/bin/sh
# Script to initialize the internal and external network via ping and arping.
# Necessary to overcome bugs in older vCloud Director versions.

# External interface
if [ "$IFACE" = eth0 ]; then
        ping -c 3 -I eth0 198.41.0.4
fi


# Internal interface
if [ "$IFACE" = eth0 ]; then
        ping -c 3 -I eth0 192.168.110.10
fi
